name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    defaults:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          path: "./front/"
          build: npm run build
          start: npm run cy:ci
